### ISSUE TITLE
AttributeError: 'SocketIOHandler' object has no attribute 'response_headers_list'

### ISSUE THREAD

**Issue by wtong2** [stephenmcd/django-socketio#63]
A fresh installation of django-socketio from the instructions results in this error.
I had this installed 6 months ago and was working till i reinstalled it.

Had tried using this in my development and production environment but to no avail.

This results in this error:

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/gevent_socketio-0.2.1-py2.7.egg/socketio/server.py", line 49, in handle
    handler.handle()
  File "/Library/Python/2.7/site-packages/gevent/pywsgi.py", line 184, in handle
    result = self.handle_one_request()
  File "/Library/Python/2.7/site-packages/gevent/pywsgi.py", line 321, in handle_one_request
    self.handle_one_response()
  File "/Library/Python/2.7/site-packages/gevent_socketio-0.2.1-py2.7.egg/socketio/handler.py", line 68, in handle_one_response
    jobs = self.transport.connect(session, request_method)
  File "/Library/Python/2.7/site-packages/gevent_socketio-0.2.1-py2.7.egg/socketio/transports.py", line 92, in connect
    self.write_packed(session_id)
  File "/Library/Python/2.7/site-packages/gevent_socketio-0.2.1-py2.7.egg/socketio/transports.py", line 19, in write_packed
    self.write(data)
  File "/Library/Python/2.7/site-packages/gevent_socketio-0.2.1-py2.7.egg/socketio/transports.py", line 22, in write
    if 'Content-Length' not in self.handler.response_headers_list:
AttributeError: 'SocketIOHandler' object has no attribute 'response_headers_list'
<Greenlet at 0x1087159b0: <bound method SocketIOServer.handle of <SocketIOServer at 0x107e29410 fileno=5 address=0.0.0.0:2222>>(<socket at 0x108741b10 fileno=[Errno 9] Bad file d, ('192.168.1.105', 58061))> failed with AttributeError
```

Please kindly assist. Thanks!

**Comment by PoopFeast6969** [comment]
The latest versions which <code>pip install django-socketio</code> installs:

<code>Django==1.8.1
django-socketio==0.3.9
gevent==1.0.1
gevent-socketio==0.2.1
gevent-websocket==0.9.3
greenlet==0.4.6
sphinx-me==0.3</code>

gives me Glideh's exact error above.
<code></code>

<code></code>
However installing wtong2's configuration with:

<code>pip install -Iv django==1.5.5 django-socketio==0.3.6 gevent-socketio==0.2.1 gevent-websocket==0.2.3 gevent==0.13.6</code>

giving me the packages:

<code>Django==1.5.5
django-socketio==0.3.6
gevent==0.13.6
gevent-socketio==0.2.1
gevent-websocket==0.2.3
greenlet==0.4.6
sphinx-me==0.3</code>

gives me the error:

<code>File "/usr/local/lib/python2.7/site-packages/gevent/__init__.py", line 41, in <module> from gevent import core
ImportError: cannot import name core</code>

Which occurs during the starting of <code>python manage.py runserver_socketio</code> seems to be a more severe problem then the error installing the latest packages gives you. As it occurs during the starting of the server not the running.

**Comment by ltsampros** [comment]
Same problem here with Django 1.8 etc.

**Comment by professorDante** [comment]
Same issue with Django 1.4.18 and install django-socketio from pip.

**Comment by alexandervlpl** [comment]
As of today, the @PoolFeast6969 combination works with Django 1.8. Here's the magic `pip` command: `pip install django-socketio==0.3.8 gevent-socketio==0.2.1 gevent-websocket==0.2.3 gevent==0.13.6`. This should really be documented: installed the application with `pip` and just spent hours trying to make it work.

**Comment by DESHRAJ** [comment]
Yeah, I agree with @alexandervlpl . I also spent several hours in just figuring out this problem. At least this should be documented. It will help a lot of other developers.

**Comment by rajasimon** [comment]
And I agree with @alexandervlpl and @DESHRAJ

**Comment by yangqiang** [comment]
Agree with @alexandervlpl , this fix the problem for me
> pip install gevent==0.13.6

**Comment by SparksFyz** [comment]
@alexandervlpl   thanks, it  really fix my problem

**Comment by Benoit-Besnier** [comment]
The solution of @alexandervlpl don't work anymore. I try a lot of things but all for naught...
